#!/usr/bin/env python

import casadi
from casadi import ssym, mul, SXFunction, vertcat

def generateSimpleCode(F, 
                       filename='casadi_cogened_function.h',
                       docstring='// This function was undocumented in the \
                                    call to generateSimpleCode at cogen time',
                       warnstring='// WARNING!!! THIS CODE WAS AUTOGENERATED; \
                                    EDIT AT YOUR PERIL!!!',
                       outputtype='int'):
    fname=filename.split('.')
    assert len(fname)==2
    fname = fname[0]

    dir1='__inline__'
    warnstring='// WARNING!!! THIS CODE WAS AUTOGENERATED; EDIT AT YOUR PERIL!!!'
    docstring='// This function gives an idea what Andrew wants casadi code export to look like'

    s = F.getDescription().split('\n')[:-1]
    for i in xrange(len(s)):
        if s[i][:2]=='@0':
            break
    s2 = s[i:]
    s3 = '\n\t'.join(s2).replace('@','r')
    body = '\t'+s3+'\n'
    regcount=F.getWorkSize();
    regdeclarations='\tdouble ' + ','.join(['r'+str(n) for n in xrange(regcount)])+';\n';
    body=regdeclarations+body;

    if outputtype=='int':
        body = body + '\treturn 0;\n'

    instring='double ** input'
    outstring='double ** output'
    proto='%s %s %s(%s, %s)'%(dir1,outputtype,fname,instring,outstring)
    declaration=proto+';\n'
    definition=proto + '\n{\n' + body + '}\n'
    code=warnstring+'\n\n'+docstring+'\n'+definition

    import os
    fd = os.open(filename,os.O_CREAT|os.O_WRONLY);
    os.write(fd,code);
    os.close(fd);

    return code

if __name__=='__main__':

    # A Simple Example Function
    a = ssym('a')
    b = ssym('b')
    c = ssym('c')
    d = ssym('d')
    f = (a+b)/c*d
    g = f*f*f
    h = f*c
    i1 = vertcat([a,b])
    i2 = vertcat([c,d])
    o1 = vertcat([f,c])
    o2 = vertcat([g])
    F = casadi.SXFunction([i1,i2],[o1,o2])
    F.init()

    F.generateCode('joel_style.c')
    code = generateSimpleCode(F,'drew_style.c')
    print(code)
    import os
    os.system('gcc -c -Wall -Werror drew_style.c')





