/*
 *    This file was auto-generated by ACADO Toolkit.
 *
 *    ACADO Toolkit -- A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008-2011 by Boris Houska, Hans Joachim Ferreau et al., K.U.Leuven.
 *    Developed within the Optimization in Engineering Center (OPTEC) under
 *    supervision of Moritz Diehl. All rights reserved.
 *
 */


extern "C"{
#include "solver.hpp"
}
#include "INCLUDE/QProblem.hpp"


int logNWSR;


long solve( void )
{
  int nWSR = QPOASES_NWSRMAX;

  QProblem example( 52,28 );
  returnValue retVal = example.init( params.H,params.g,params.A,params.lb,params.ub,params.lbA,params.ubA, nWSR,vars.y );

  example.getPrimalSolution( vars.x );
  example.getDualSolution( vars.y );

  logNWSR = nWSR;

  return (long) retVal;
}
