/*
 *    This file was auto-generated by ACADO Toolkit.
 *
 *    ACADO Toolkit -- A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008-2011 by Boris Houska, Hans Joachim Ferreau et al., K.U.Leuven.
 *    Developed within the Optimization in Engineering Center (OPTEC) under
 *    supervision of Moritz Diehl. All rights reserved.
 *
 */


#ifndef SOLVER_QPOASES_H
#define SOLVER_QPOASES_H

#include <stdio.h>
#include <math.h>


#define QPOASES_NVMAX      52
#define QPOASES_NCMAX      110
#define QPOASES_NWSRMAX    486
#define QPOASES_PRINTLEVEL PL_NONE
#define QPOASES_EPS        2.221e-16

typedef double real_t;

typedef struct Params_t {
real_t H[2704];
real_t A[5720];
real_t g[52];
real_t lb[52];
real_t ub[52];
real_t lbA[110];
real_t ubA[110];
} Params;

typedef struct Vars_t {
real_t x[52];
real_t y[162];
} Vars;

extern Params params;
extern Vars vars;

long solve(void);

#endif
