
/// Base class
#include "TelemetryBase.hpp"
/// Custom data type used by OROCOS
#include "types/McuHandlerDataType.hpp"
/// Protobuf header, autogenerated
#include "McuHandlerTelemetry.pb.h"

class McuHandlerTelemetry
  : public TelemetryBase<McuHandlerDataType, McuHandlerProto::McuHandlerMsg>
{
  typedef TelemetryBase<McuHandlerDataType, McuHandlerProto::McuHandlerMsg> Base;

public:
  McuHandlerTelemetry(std::string name)
    : Base( name )
  {}

  ~McuHandlerTelemetry()
  {}

protected:

  virtual void fill();

};

void McuHandlerTelemetry::fill()
{
  msg.set_gyro_x( data.gyro_x );
  msg.set_gyro_y( data.gyro_y );
  msg.set_gyro_z( data.gyro_z );

  msg.set_accl_x( data.accl_x );
  msg.set_accl_y( data.accl_y );
  msg.set_accl_z( data.accl_z );

  msg.set_ua1( data.ua1 );
  msg.set_ua2( data.ua2 );
  msg.set_ue( data.ue );

  msg.set_ts_trigger( (double)((uint64_t)data.ts_trigger - startTime) * 1e-9);
  msg.set_ts_elapsed( data.ts_elapsed );
}

ORO_CREATE_COMPONENT_LIBRARY()
ORO_LIST_COMPONENT_TYPE( McuHandlerTelemetry )
//ORO_CREATE_COMPONENT( McuHandlerTelemetry )
