%%
%%    This file was auto-generated by ACADO Toolkit.
%%
%%    ACADO Toolkit -- A Toolkit for Automatic Control and Dynamic Optimization.
%%    Copyright (C) 2008-2011 by Boris Houska, Hans Joachim Ferreau et al., K.U.Leuven.
%%    Developed within the Optimization in Engineering Center (OPTEC) under
%%    supervision of Moritz Diehl. All rights reserved.
%%


IFLAGS  = [ '-I. -I./qpoases/INCLUDE  -I./qpoases/SRC ' ];

if ( ispc == 0 )
%     CPPFLAGS  = [ IFLAGS, '-D__cpluplus -O -DLINUX -g ' ];
    CPPFLAGS  = [ IFLAGS, '-D__cpluplus -DLINUX -g ' ];
else
%     CPPFLAGS  = [ IFLAGS, '-D__cpluplus -DWIN32 -g ' ];
    CPPFLAGS  = [ IFLAGS, '-D__cpluplus -O -DWIN32 -g ' ];
end

OBJECTS = [ './qpoases/SRC/QProblem.cpp ',...
            './qpoases/SRC/QProblemB.cpp ',...
            './qpoases/SRC/Bounds.cpp ',...
            './qpoases/SRC/Constraints.cpp ',...
            './qpoases/SRC/SubjectTo.cpp ',...
            './qpoases/SRC/Indexlist.cpp ',...
            './qpoases/SRC/CyclingManager.cpp ',...
            './qpoases/SRC/Utils.cpp ',...
            './qpoases/SRC/MessageHandling.cpp ',...
            './qpoases/solver.cpp ',...
            'integrator.c ',...
            'condensing.c ',...
            'gauss_newton_method.c '];


eval( [ 'mex -output MHEstep CFLAGS="\$CFLAGS -std=c99" ', CPPFLAGS, 'MHEmex.c ', OBJECTS] );
% eval( [ 'mex -output MHEstep ', CPPFLAGS, 'MHEmex.c ', OBJECTS] );
disp( [ 'MHEstep.', eval('mexext'), ' successfully created!'] );

clear IFLAGS CPPFLAGS OBJECTS

