#!/bin/bash

# Run the script in valgrind, which is able to hunt down the myriad processes
# and cut through the layers of orocos abstraction, and tell you where your
# code is actually Segfaulting

valgrind --trace-children=yes bash ./runLEDTracker.sh
