/*
 *    This file was auto-generated by ACADO Toolkit.
 *
 *    ACADO Toolkit -- A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008-2011 by Boris Houska, Hans Joachim Ferreau et al., K.U.Leuven.
 *    Developed within the Optimization in Engineering Center (OPTEC) under
 *    supervision of Moritz Diehl. All rights reserved.
 *
 */


#include "acado.h"


#include "auxiliary_functions.c"


/* SOME CONVENIENT DEFINTIONS: */
/* --------------------------------------------------------------- */
   #define NX          22      /* number of differential states  */
   #define NU          3      /* number of control inputs       */
   #define NP          35      /* number of fixed parameters     */
   #define N           10      /* number of control intervals    */
   #define NUM_STEPS   5      /* number of real time iterations */
   #define VERBOSE     1      /* show iterations: 1, silent: 0  */
/* --------------------------------------------------------------- */


/* GLOBAL VARIABLES FOR THE ACADO REAL-TIME ALGORITHM: */
/* --------------------------------------------------- */
   ACADOvariables acadoVariables;
   ACADOworkspace acadoWorkspace;

/* GLOBAL VARIABLES FOR THE QP SOLVER: */
/* ----------------------------------- */
   Vars         vars;
   Params       params;


/* A TEMPLATE FOR TESTING THE REAL-TIME IMPLEMENTATION: */
/* ---------------------------------------------------- */
int main(){

   /* INTRODUCE AUXILIARY VAIRABLES: */
   /* ------------------------------ */
      int    i, iter        ;
      real_t measurement[NX];


   /* INITIALIZE THE STATES AND CONTROLS: */
   /* ---------------------------------------- */
      for( i = 0; i < NX*N; ++i )  acadoVariables.x[i] = 0.0;
      for( i = 0; i < NU*N; ++i )  acadoVariables.u[i] = 0.0;
      for( i = 0; i < NP; ++i )  acadoVariables.p[i] = 0.0;

   /* // INITIALIZE THE STATES AND CONTROL REFERENCE: */
   /* // -------------------------------------------- */
      for( i = 0; i < NX*N; ++i )  acadoVariables.xRef[i]  =  0.0;
      for( i = 0; i < NU*N; ++i )  acadoVariables.uRef[i]  =  0.0;


   /* SETUP THE FIRST STATE MEASUREMENT: */
   /* ------------------------------------------------ */
      for( i = 0; i < NX; ++i )  measurement[i] = 0.0;

      acadoVariables.x[0] = 1.0;
      measurement     [0] = 1.0;

      if( VERBOSE ) printHeader();


   /* PREPARE FIRST STEP: */
   /* ------------------- */
      preparationStep();


   /* GET THE TIME BEFORE START THE LOOP: */
   /* ---------------------------------------------- */
      real_t t1 = getTime();


   /* THE REAL-TIME ITERATION LOOP: */
   /* ---------------------------------------------- */
      for( iter = 0; iter < NUM_STEPS; ++iter ){

        /* TAKE A MEASUREMENT: */
        /* ----------------------------- */
           /// meausrement = ...

        /* PERFORM THE FEEDBACK STEP: */
        /* ----------------------------- */
           feedbackStep( measurement );

        /* APPLY THE NEW CONTROL IMMEDIATELY TO THE PROCESS: */
        /* ------------------------------------------------- */
           /// send first piece of acadoVariables.u to process;
           if( VERBOSE ) printf("=================================================================\n\n" );
           if( VERBOSE ) printf("      Real-Time Iteration %d:  KKT Tolerance = %.3e\n", iter, getKKT() );
           if( VERBOSE ) printf("\n=================================================================\n" );

        /* OPTIONAL: SHIFT THE INITIALIZATION: */
        /* ----------------------------------- */
           /// shiftControls( acadoVariables.uRef );
           /// shiftStates  ( acadoVariables.xRef );

        /* PREPARE NEXT STEP: */
        /* ------------------ */
           preparationStep();
      }
      if( VERBOSE ) printf("\n\n              END OF THE REAL-TIME LOOP. \n\n\n");


   /* GET THE TIME AT THE END OF THE LOOP: */
   /* ---------------------------------------------- */
      real_t t2 = getTime();


   /* PRINT DURATION AND RESULTS: */
   /* -------------------------------------------------------------------------------------------------- */
      if( !VERBOSE )
      printf("\n\n AVERAGE DURATION OF ONE REAL-TIME ITERATION:   %.3g μs\n\n", 1e6*(t2-t1)/NUM_STEPS );

      printStates();
      printControls();

    return 0;
}
