/* Auto-generated by genmsg_cpp for file /home/kurt/planepower/components/lowlevel/soem/soem_ebox/msg/EBOXAnalog.msg */
#ifndef SOEM_EBOX_MESSAGE_EBOXANALOG_H
#define SOEM_EBOX_MESSAGE_EBOXANALOG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
//#include "ros/serialization.h"
//#include "ros/builtin_message_traits.h"
//#include "ros/message_operations.h"
//#include "ros/time.h"

//#include "ros/macros.h"

//#include "ros/assert.h"


namespace soem_ebox
{
template <class ContainerAllocator>
struct EBOXAnalog_ {
  typedef EBOXAnalog_<ContainerAllocator> Type;

  EBOXAnalog_()
  : analog()
  {
    analog.assign(0.0);
  }

  EBOXAnalog_(const ContainerAllocator& _alloc)
  : analog()
  {
    analog.assign(0.0);
  }

  typedef boost::array<float, 2>  _analog_type;
  boost::array<float, 2>  analog;


  typedef boost::shared_ptr< ::soem_ebox::EBOXAnalog_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::soem_ebox::EBOXAnalog_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct EBOXAnalog
typedef  ::soem_ebox::EBOXAnalog_<std::allocator<void> > EBOXAnalog;

typedef boost::shared_ptr< ::soem_ebox::EBOXAnalog> EBOXAnalogPtr;
typedef boost::shared_ptr< ::soem_ebox::EBOXAnalog const> EBOXAnalogConstPtr;


} // namespace soem_ebox

#endif // SOEM_EBOX_MESSAGE_EBOXANALOG_H

