/*
 *    This file was auto-generated by ACADO Toolkit.
 *
 *    ACADO Toolkit -- A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008-2011 by Boris Houska, Hans Joachim Ferreau et al., K.U.Leuven.
 *    Developed within the Optimization in Engineering Center (OPTEC) under
 *    supervision of Moritz Diehl. All rights reserved.
 *
 */


#ifndef SOLVER_QPOASES_H
#define SOLVER_QPOASES_H

#include <stdio.h>
#include <math.h>


#define QPOASES_NVMAX      10
#define QPOASES_NCMAX      60
#define QPOASES_NWSRMAX    210
#define QPOASES_PRINTLEVEL PL_NONE
#define QPOASES_EPS        2.221e-16

typedef double real_t;

typedef struct Params_t {
real_t H[100];
real_t A[600];
real_t g[10];
real_t lb[10];
real_t ub[10];
real_t lbA[60];
real_t ubA[60];
} Params;

typedef struct Vars_t {
real_t x[10];
real_t y[70];
} Vars;

extern Params params;
extern Vars vars;

long solve(void);

#endif
