/// Base class
#include "TelemetryBase.hpp"
/// Custom data type used by OROCOS
#include "types/WinchControlDataType.hpp"
/// Protobuf header, autogenerated
#include "WinchControlTelemetry.pb.h"

class WinchControlTelemetry
  : public TelemetryBase<WinchControlDataType, WinchControlProto::WinchControlMsg>
{
  typedef TelemetryBase<WinchControlDataType, WinchControlProto::WinchControlMsg> Base;

public:
  WinchControlTelemetry(std::string name)
    : Base( name )
  {}

  ~WinchControlTelemetry()
  {}

protected:

  virtual void fill();

};

void WinchControlTelemetry::fill()
{
  msg.set_length( data.length );
  msg.set_speed( data.speed );

  msg.set_dbg_theta( data.dbg_theta );
  msg.set_dbg_omega( data.dbg_omega );
  msg.set_dbg_current( data.dbg_current );
  
  msg.set_ts_trigger(data.ts_trigger * 1e-9);
  msg.set_ts_elapsed( data.ts_elapsed );
}

ORO_CREATE_COMPONENT_LIBRARY()
ORO_LIST_COMPONENT_TYPE( WinchControlTelemetry )
