#!/usr/bin/env python
from parse_cpf import parse_cpf

def cpf2cpp_defines(infile,outfile):
	proplist = parse_cpf(infile)
	lines = ['// WARNING!!! AUTOGENERATED CODE SNIPPET!!!']
	for name,ty,value in proplist:
		lines.append('#define %s %s'%(name,value))
	outtext = '\n'.join(lines) + '\n'
	open(outfile,'w').write(outtext)

if __name__=='__main__':
	infile = 'sample.cpf'
	outfile = 'sample_defines.hpp'
	cpf2cpp_defines(infile,outfile)

	


