#!/usr/bin/env python
from parse_cpf import parse_cpf

def cpf2dat(infile,outfile):
	proplist = parse_cpf(infile)
	lines = []
	#lines.append('// WARNING!!! AUTOGENERATED CODE SNIPPET!!!')
	for name,ty,value in proplist:
		lines.append('%s'%value)
	outtext = '\n'.join(lines) + '\n'
	open(outfile,'w').write(outtext)

if __name__=='__main__':
	infile = 'sample.cpf'
	outfile = 'sample.cpf.dat'
	cpf2dat(infile,outfile)

