#!/usr/bin/env bash

# This is just a slightly more convenient wrapper around greg's 
# rapidly evolving 3d visualizer in haskell

# Our DNS is fucked up... pull carousl ip address from /etc/hosts
ip=`egrep 'carousel|planepower-pc' /etc/hosts | head -1 | cut --delimiter=' ' -f1`

CMD="$PLANEPOWER_ROOT/rawesome_stuff/rawesome/plotter/dist/build/plot-ho-matic/plot-ho-matic --ip tcp://$ip:5563"

echo $0: running $CMD...
$CMD
