#!/usr/bin/env bash

# This is just a slightly more convenient wrapper around greg's 
# rapidly evolving 3d visualizer in haskell

# Our DNS is fucked up... pull carousl ip address from /etc/hosts
ip=`egrep 'carousel|planepower-pc' /etc/hosts | head -1 | cut --delimiter=' ' -f1`
#$PLANEPOWER_ROOT is defined in env.sh, which is currently in the tuplified branch. Source it in your bashrc
CMD="$PLANEPOWER_ROOT/rawesome_stuff/wtfviz/dist/build/mhe-mpc/mhe-mpc --ip tcp://$ip:5563 "

echo $0: running $CMD...
$CMD &disown
