/* Auto-generated by genmsg_cpp for file /home/kurt/planepower/components/lowlevel/soem/soem_ebox/msg/EBOXDigital.msg */
#ifndef SOEM_EBOX_BOOST_SERIALIZATION_EBOXDIGITAL_H
#define SOEM_EBOX_BOOST_SERIALIZATION_EBOXDIGITAL_H

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/nvp.hpp>
#include <soem_ebox/EBOXDigital.h>

namespace boost
{
namespace serialization
{

template<class Archive, class ContainerAllocator>
void serialize(Archive& a,  ::soem_ebox::EBOXDigital_<ContainerAllocator>  & m, unsigned int)
{
    a & make_nvp("digital",m.digital);
}

} // namespace serialization
} // namespace boost

#endif // SOEM_EBOX_BOOST_SERIALIZATION_EBOXDIGITAL_H

